#!/usr/bin/env bash
#This script will print Best School 10 times with Hi insterted after the ninth line
i=0
while [ $i -lt 11 ]
do
      echo Best School
      if [ $i = 9 ]
      then
	  echo Hi
      fi
i=$((i + 1))      
done
