#!/usr/bin/env bash
#This script will display a timer that shows the hour and a line for every minute.
hour=0
while [ $hour -le 12 ]
do echo "Hour: $hour"
   ((hour++))
 min=1
   while [ $min -le 59 ]
   do echo $min
      ((min++))
   done
done
