#!/usr/bin/env bash
#To file or not
NAME=school

if [ -e $NAME ]
then
	 echo "school file exists"
else
    echo "school file does not exist"
fi    
    
     if [ -s $NAME ]
     then
	     echo "school file is not empty"
     else
	     echo "school file is empty"
     fi 
	     if [ -f $NAME ]    
           then
	       echo "school is a regular file"
	   fi   
     

