#!/usr/bin/env bash
#To file or not
NAME=school

if [ -e $NAME ]
then
    echo "school file exists"
    
else
    echo "school file does not exist"
    if [ -f $NAME ]
    then
	echo "school file is a regular file"
   fi

    if [ -s $NAME ] 
    then
	echo "school file is not empty"
    else
	echo "school file is empty"
    fi

fi
